wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret dns_domain
  reboot_timeout: ${reboot_timeout}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret fallback_ap_password
    ssid: ${fallback_ap_ssid}

<<: !include .base_nowifi.yaml

captive_portal:
