
substitutions:
  mqtt_topic_prefix: blinktest1

mqtt:
  id: mqttclient
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  reboot_timeout: "0s"
  topic_prefix: ${mqtt_topic_prefix}

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin

ota:

web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  power_pin: GPIO12
  phy_addr: 1
  domain: !secret dns_domain

esphome:
  name: blinktest1
  platform: ESP32
  board: esp32dev

logger:
  baud_rate: 115200
  level: DEBUG


i2c:
  sda: 13
  scl: 16
  scan: true
  id: bus_a

sensor:
  - platform: bmp280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    address: 0x76
    update_interval: 60s


interval:
  - interval: 500ms
    then:
      - light.toggle: led

light:
  - platform: monochromatic
    output: led_output
    id: led
    default_transition_length: 0s
    internal: true

output:
  - platform: ledc
    pin: 2
    frequency: 1000 Hz
    id: led_output
