
substitutions:
  fallback_ap_ssid: "Gridmeter2"
  mqtt_topic_prefix: gridmeter2
  reboot_timeout: 15min

<<: !include .base_nowifi.yaml 

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  power_pin: GPIO12
  phy_addr: 0
  domain: !secret dns_domain

esphome:
  name: gridmeter2
  platform: ESP32
  board: esp32dev

logger:
  baud_rate: 115200
  level: INFO

uart:
  - id: meter_in
    rx_pin:
      number: 32
      inverted: false
      mode:
        input: true
        pullup: false
    tx_pin:
      number: TX
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1
    rx_buffer_size: 512
    debug:
#      dummy_receiver: true
      direction: RX
      after:
        timeout: 150ms
        bytes: 1024
      sequence:
        - uart.write: !lambda return bytes;
        - lambda: id(mqttclient).publish("gridmeter2/sensor/sml/state", format_hex(bytes));
#        - lambda: UARTDebug::log_hex(direction, bytes, 0);

sml:
  - id: sml0
    uart_id: meter_in

sensor:
  - platform: sml
    retain: false
    name: "powerTotal"
    id: "powerTotal"
    sml_id: sml0
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 2
    device_class: energy
    filters:
      - multiply: 0.01
  - platform: sml
    retain: false
    name: "energyImportTotal"
    id: "energyImportTotal"
    sml_id: sml0
    obis_code: "1-0:1.8.0"
    unit_of_measurement: Wh
    accuracy_decimals: 3
    device_class: energy
    filters:
      - multiply: 0.00000001
    on_value:
      - binary_sensor.template.publish:
          id: led_delayed_off
          state: ON
      - binary_sensor.template.publish:
          id: led_delayed_off
          state: OFF
  - platform: sml
    retain: false
    name: "energyExportTotal"
    id: "energyExportTotal"
    sml_id: sml0
    obis_code: "1-0:2.8.0"
    unit_of_measurement: Wh
    accuracy_decimals: 3
    device_class: energy
    filters:
      - multiply: 0.00000001

binary_sensor:
  - platform: template
    id: led_delayed_off
    filters:
      - delayed_off: 100ms
    on_press:
      then:
        - light.turn_on:
            id: led
            brightness: 30%
    on_release:
      then:
        - light.turn_off: led

light:
  - platform: monochromatic
    output: led_output
    id: led
    default_transition_length: 0s
    internal: true

output:
  - platform: ledc
    pin: 2
    frequency: 1000 Hz
    id: led_output
