# einfacher Raumsensor
# 
# Hardware:
# - NodeMCU Devboard
# - DS18S20 Temperatursensor
#   GND: an GND
#   VCC: an 3.3V
#   DATA: an D4

substitutions:
  fallback_ap_ssid: "Poolsensor"
  mqtt_topic_prefix: poolsensor
  reboot_timeout: 15min

<<: !include .base.yaml


esphome:
  name: poolsensor
  platform: ESP8266
  board: nodemcu
  esp8266_restore_from_flash: false


one_wire:
  - platform: gpio
    pin: D4

sensor:
  - platform: dallas_temp
    resolution: 10
    id: temp
    name: "Temperatur"
