# einfacher Raumsensor
# 
# Hardware:
# - NodeMCU Devboard
# - BME680 Raumsensor
#   GND: an GND
#   VCC: an 3.3V
#   SDA: an D3
#   SCL: an D4

substitutions:
  fallback_ap_ssid: "Raumsensor9"
  mqtt_topic_prefix: raumsensor9

<<: !include .base.yaml


esphome:
  name: raumsensor9
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: false

i2c:
  sda: D3
  scl: D4
  scan: true
  id: bus_a

bme680_bsec:
  i2c_id: bus_a
  address: 0x77
  temperature_offset: 0
  iaq_mode: static
  sample_rate: lp
  state_save_interval: 6h

sensor:
  - platform: bme680_bsec
    temperature:
      # Temperature in °C
      name: "BME680 Temperature"
      sample_rate: lp
      filters:
        - median
    pressure:
      # Pressure in hPa
      name: "BME680 Pressure"
      sample_rate: lp
      filters:
        - median
    humidity:
      # Relative humidity %
      name: "BME680 Humidity"
      sample_rate: lp
      filters:
        - median
    gas_resistance:
      # Gas resistance in Ω
      name: "BME680 Gas Resistance"
      filters:
        - median
    iaq:
      # Indoor air quality value
      name: "BME680 IAQ"
      filters:
        - median
    iaq_accuracy:
      # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: "BME680 Numeric IAQ Accuracy"
    co2_equivalent:
      # CO2 equivalent estimate in ppm
      name: "BME680 CO2 Equivalent"
      filters:
        - median
    breath_voc_equivalent:
      # Volatile organic compounds equivalent estimate in ppm
      name: "BME680 Breath VOC Equivalent"
      filters:
        - median
