# einfacher Raumsensor, Schlafzimmer
# 
# Hardware:
# - NodeMCU Devboard
# - BME280 Temperatur- und Luftfeuchte- und Luftdrucksensor
#   GND: an GND
#   VCC: an 3.3V
#   SCA: an D5
#   SCL: an D6

substitutions:
  fallback_ap_ssid: "Raumsensor4"
  mqtt_topic_prefix: raumsensor4
  reboot_timeout: 15min

<<: !include .base.yaml

esphome:
  name: raumsensor4
  platform: ESP8266
  board: nodemcu
  esp8266_restore_from_flash: false

i2c:
  sda: D5
  scl: D6
  scan: true

sensor:
  - platform: bme280
    address: 0x76
    temperature:
      name: "Temperatur"
      retain: false
    pressure:
      name: "Luftdruck"
      retain: false
    humidity:
      name: "Luftfeuchte"
      retain: false
