# einfacher Raumsensor, Kind 1
# 
# Hardware:
# - NodeMCU Devboard
# - DS18S20 Temperatursensor
#   GND: an GND
#   VCC: an 3.3V
#   DATA: an D5

substitutions:
  fallback_ap_ssid: "Raumsensor1"
  mqtt_topic_prefix: raumsensor1
  reboot_timeout: 15min

<<: !include .base.yaml


esphome:
  name: raumsensor1
  platform: ESP8266
  board: nodemcu
  esp8266_restore_from_flash: false

dallas:
  - pin: D5

sensor:
  - platform: dallas
    index: 0
    resolution: 10
    id: temp
    name: "Temperatur"
    retain: false
