# https://www.esphome-devices.com/devices/gosund-sp112/
# https://community.home-assistant.io/t/esphome-and-blitzwolf-shp5/144296/3

substitutions:
  fallback_ap_ssid: "steckdose-0590"
  mqtt_topic_prefix: steckdose/0590

<<: !include .base.yaml

esphome:
  name: steckdose-0590
  platform: ESP8266
  board: esp8285
  build_path: build/steckdose-0590/
  on_boot:
    priority: -10
    # Turn on switch during startup
    then:
      - switch.turn_on: switch1

logger:
  baud_rate: 0 # do not log on serial, it causes a boot loop with uart
  logs:
    sensor: INFO
    adc: INFO

uart:
  rx_pin: RX
  baud_rate: 4800

status_led:
  pin:
    number: GPIO02
    inverted: true

output:
- platform: gpio
  id: led1
  pin:
    number: GPIO00
    inverted: true

switch:
- platform: gpio
  name: "Relay Mains"
  id: switch1
  pin: GPIO14
  on_turn_on:
    - output.turn_on: led1
  on_turn_off:
    - output.turn_off: led1
- platform: gpio
  name: "Relay USB"
  id: switchusb
  pin:
    number: GPIO13
    inverted:  true
  restore_mode: RESTORE_DEFAULT_ON

binary_sensor:
- platform: gpio
  id: button1
  pin:
    number: GPIO16
    inverted: true
  on_click:
  # short button press toggles mains
  - min_length: 10ms
    max_length: 250ms
    then:
    - switch.toggle: switch1
  # long button press toggles USB
  - min_length: 250ms
    max_length: 1000ms
    then:
    - switch.toggle: switchusb

sensor:
- platform: total_daily_energy
  name: "Total Daily Energy"
  power_id: wattage
- platform: cse7766
  current:
    id: amperage
    name: Amperage
    accuracy_decimals: 3
  voltage:
    id: voltage
    name: Voltage
    accuracy_decimals: 1
  power:
    id: wattage
    name: Wattage
    accuracy_decimals: 0
