# https://www.esphome-devices.com/devices/gosund-sp112/
# https://community.home-assistant.io/t/esphome-and-blitzwolf-shp5/144296/3

substitutions:
  fallback_ap_ssid: "steckdose-schuppenheizung"
  mqtt_topic_prefix: steckdose/schuppenheizung
  reboot_timeout: 15min
  update_interval: 15s

<<: !include .base.yaml

esphome:
  name: steckdose-schuppenheizung
  platform: ESP8266
  board: esp8285
  build_path: build/steckdose-schuppenheizung/
  on_boot:
    priority: -10
    # Turn off heating during startup
    then:
      - switch.turn_off: switch1

logger:
  baud_rate: 0 # do not log on serial, it causes a boot loop with uart
  level: INFO

uart:
  rx_pin: GPIO03
  baud_rate: 4800
  parity: EVEN


status_led:
  pin:
    number: GPIO02
    inverted: true


one_wire:
  - platform: gpio
    id: pin_temp
    pin: GPIO13


output:
- platform: gpio
  id: led1
  pin:
    number: GPIO00
    inverted: true

switch:
- platform: gpio
  name: "Relay Mains"
  id: switch1
  pin: GPIO14
  on_turn_on:
    - output.turn_on: led1
  on_turn_off:
    - output.turn_off: led1
- platform: gpio
  name: "Relay USB"
  id: switchusb
  pin:
    number: GPIO05
  restore_mode: RESTORE_DEFAULT_ON

binary_sensor:
- platform: gpio
  id: button1
  pin:
    number: GPIO16
    inverted: true
  on_click:
  # short button press toggles mains
  - min_length: 10ms
    max_length: 250ms
    then:
    - switch.toggle: switch1
  # long button press toggles USB
  - min_length: 1000ms
    max_length: 5000ms
    then:
    - switch.toggle: switchusb

number:
- platform: template
  name: "Temp Schuppen Frostschutz Soll"
  id: schuppen_frostschutz_soll
  optimistic: true
  unit_of_measurement: °C
  update_interval: ${update_interval}
  initial_value: 3
  min_value: 2
  max_value: 18
  restore_value: true
  step: 1

sensor:
- platform: dallas_temp
  one_wire_id: pin_temp
  resolution: 10
  id: schuppen_frostschutz
  name: "Temp Schuppen Frostschutz"
  retain: false
  update_interval: ${update_interval}
  filters:
  - lambda: |-
      if (x <= 84) return x;
      else return {};
  on_value:
    then:
    - if:
        condition:
          lambda: |-
            return x < id(schuppen_frostschutz_soll).state;
        then:
        - switch.turn_on: switch1
    - if:
        condition:
          lambda: |-
            return x >= (id(schuppen_frostschutz_soll).state + 3);
        then:
        - switch.turn_off: switch1
        


- platform: total_daily_energy
  name: "Total Daily Energy"
  power_id: power
  filters:
  - throttle: ${update_interval}
- platform: cse7766
  current:
    id: amperage
    name: Amperage
    accuracy_decimals: 2
    filters:
    - calibrate_linear:
      - 0.0 -> 0.0
      - 8.37 -> 9.24
    - throttle_average: ${update_interval}
  voltage:
    id: voltage
    name: Voltage
    accuracy_decimals: 1
    filters:
    - calibrate_linear:
      - 0.0 -> 0.0
      - 121.8 -> 225
      - 123.6 -> 227
    - throttle_average: ${update_interval}
  power:
    id: power
    name: Power
    accuracy_decimals: 0
    filters:
    - calibrate_linear:
      - 0.0 -> 0.0
      - 1015 -> 2090
    - throttle: ${update_interval}
  energy:
    name: Energy
    accuracy_decimals: 0
