# Lichtsteuerung Weihnachts-Licherketten (5V)
# 
# Hardware:
# - D1 Mini
# - 5V USB Netzteil
#   5V+ an Pluspol der LED-Stripes
# - IRLZ44N MOSFET Pins (von vorne betrachtet von links nach rechts): G D S
#   G: direkt an Digital-Out GPIO5 des NodeMCU (kein Wiederstand nötig) sowie mit 10k gegen GND
#   D: Liefert die geschaltete Masse der Leuchstreifen. Minuspol der Stripes hier anschließen
#   S: an GND

substitutions:
  fallback_ap_ssid: "Weichnachten Lichterkette 2"
  mqtt_topic_prefix: licht/weihnachten_lichterkette2
  reboot_timeout: 15min

<<: !include .base.yaml

esphome:
  name: weihnachten_lichterkette2
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: false

light:
  - platform: monochromatic
    id: light1
    output: output_light1
    restore_mode: ALWAYS_OFF
    name: light1

output:
  - platform: esp8266_pwm
    id: output_light1
    pin: GPIO5
    frequency: 1000 Hz
